// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// For local dev with local Supabase (PostgreSQL) or local Postgres proxy:
// - Set in .env.local: VITE_SUPABASE_URL, VITE_SUPABASE_PUBLISHABLE_KEY
// - If not set, this defaults to local Supabase emulator values.

const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ||
  'http://127.0.0.1:54321';
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.localanon';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});